import { brand } from "./brand";
import { formatCurrency, formatDate } from "./utils";
import type { DocConfig } from "./docConfigs";
import type { Doc } from "./store";

const baseStyles = `
  * { box-sizing: border-box; font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; }
  body { margin: 0; padding: 32px; color: #1f2937; }
  .head { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0a8dc7; padding-bottom:16px; margin-bottom:24px; }
  .brand { font-size:26px; font-weight:900; }
  .brand .a { color:#0a8dc7; } .brand .b { color:#9ed24d; }
  .muted { color:#6b7280; font-size:12px; }
  h1 { font-size:20px; margin:0 0 4px; }
  .meta { text-align:right; font-size:13px; }
  .meta b { color:#111827; }
  .grid { display:grid; grid-template-columns:1fr 1fr; gap:16px; margin-bottom:20px; }
  .box { border:1px solid #e5e7eb; border-radius:10px; padding:12px 14px; }
  .box .lbl { font-size:11px; text-transform:uppercase; letter-spacing:.04em; color:#9ca3af; margin-bottom:4px; }
  table { width:100%; border-collapse:collapse; margin-top:8px; }
  th { background:#0a8dc7; color:#fff; text-align:left; padding:10px; font-size:12px; }
  th.r, td.r { text-align:right; }
  td { padding:10px; border-bottom:1px solid #eee; font-size:13px; }
  .totals { margin-top:16px; margin-left:auto; width:280px; }
  .totals .row { display:flex; justify-content:space-between; padding:6px 0; font-size:14px; }
  .totals .grand { border-top:2px solid #111; font-weight:800; font-size:16px; margin-top:6px; padding-top:10px; }
  .notes { margin-top:24px; font-size:12px; color:#6b7280; }
  .foot { margin-top:40px; text-align:center; color:#9ca3af; font-size:11px; border-top:1px solid #eee; padding-top:12px; }
`;

function open(title: string, inner: string) {
  const w = window.open("", "_blank", "width=900,height=800");
  if (!w) {
    alert("Please allow pop-ups to print.");
    return;
  }
  w.document.write(
    `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>${baseStyles}</style></head><body>${inner}</body></html>`
  );
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 250);
}

export function printDocument(config: DocConfig, d: Doc) {
  const lines: { item: string; qty: number; rate: number }[] = d.lines || [];
  const rows = lines
    .map(
      (l) =>
        `<tr><td>${l.item || ""}</td><td class="r">${l.qty}</td><td class="r">${formatCurrency(l.rate)}</td><td class="r">${formatCurrency(l.qty * l.rate)}</td></tr>`
    )
    .join("");

  const itemsTable = config.itemized
    ? `<table><thead><tr><th>Item</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr></thead><tbody>${rows || `<tr><td colspan="4" style="text-align:center;color:#9ca3af">No line items</td></tr>`}</tbody></table>`
    : `<div class="box"><div class="lbl">Amount</div><div style="font-size:20px;font-weight:800">${formatCurrency(Number(d.amount || d.total || 0))}</div></div>`;

  const inner = `
    <div class="head">
      <div>
        <div class="brand"><span class="a">${brand.wordmarkPrimary}</span> <span class="b">${brand.wordmarkAccent}</span></div>
        <div class="muted">${brand.fullName}</div>
      </div>
      <div class="meta">
        <h1>${config.title}</h1>
        <div><b>${d.number || "-"}</b></div>
        <div class="muted">${d.date ? formatDate(d.date) : ""}</div>
      </div>
    </div>
    <div class="grid">
      ${config.party !== "none" ? `<div class="box"><div class="lbl">${config.party === "customer" ? "Customer" : "Vendor"}</div><div><b>${d.party || "-"}</b></div></div>` : `<div></div>`}
      <div class="box"><div class="lbl">Reference</div><div>${d.reference || "-"}</div></div>
    </div>
    ${itemsTable}
    <div class="totals">
      <div class="row grand"><span>Total</span><span>${formatCurrency(Number(d.total || 0))}</span></div>
    </div>
    ${d.notes ? `<div class="notes"><b>Notes:</b> ${d.notes}</div>` : ""}
    <div class="foot">Generated by ${brand.fullName} • ${brand.tagline}</div>
  `;
  open(`${config.title} ${d.number || ""}`, inner);
}

export function printTable(title: string, columns: { key: string; label: string }[], rows: Doc[]) {
  const head = columns.map((c) => `<th>${c.label}</th>`).join("");
  const body = rows.length
    ? rows.map((r) => `<tr>${columns.map((c) => `<td>${r[c.key] ?? ""}</td>`).join("")}</tr>`).join("")
    : `<tr><td colspan="${columns.length}" style="text-align:center;color:#9ca3af;padding:24px">No records</td></tr>`;
  const inner = `
    <div class="head">
      <div><div class="brand"><span class="a">${brand.wordmarkPrimary}</span> <span class="b">${brand.wordmarkAccent}</span></div><div class="muted">${brand.fullName}</div></div>
      <div class="meta"><h1>${title}</h1></div>
    </div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
    <div class="foot">Generated by ${brand.fullName} • ${brand.tagline}</div>
  `;
  open(title, inner);
}
